consensus:
  min_validators: 2
  quorum_percentage: 0.66
  type: PoAIP
genesis_file: ../genesis.json
network:
  bootstrap_nodes:
  - 192.168.1.129:18333
  - 192.168.1.132:18333
  external_ip: 192.168.1.132
  listen_ip: 0.0.0.0
  listen_port: 18333
  network_id: playergold-testnet-genesis
  network_type: testnet
node:
  data_dir: ./data/testnet/node2
  is_validator: true
  node_id: validator-node-2
  validator_address: PGc7e5fd6bd3d80eead6a828e32b2cbb27497997
